version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=devoted.loc
      - NGINX_PORT=80
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './:/var/www/devoted'
      - './logs/nginx:/var/log/nginx'
  php:
    build:
      context: .
      dockerfile: './docker/php/Dockerfile'
    container_name: php
    working_dir: /var/www/devoted
    volumes:
      - './:/var/www/devoted'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: devoted
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
